project:
  type: website
  output-dir: docs

website:
  favicon: "img/HDS.png"
  title: "Harper Data Science"
  sidebar:
    logo: "img/HDS.png"
    style: "docked"
    search: true
    contents: 
      - section: "Information"
        contents:
          - index.qmd
          - about.qmd
#      - section: "HARUG!"
#        contents:
#         - d20221005.qmd
#         - d20220921.qmd

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

